### ISSUE TITLE
Question about modality label

### ISSUE THREAD

**Issue by lxa9867** [uni-medical/IMIS-Bench#2]
Hi Authors,

Thanks for sharing this work.

I have a question about the modality label in the dataset.json. Does the label indicate the categories in Fig 2.a? or in other word, is that possible to have a category label for the images in the organized dataset? Thank you.

![image](https://github.com/user-attachments/assets/b017d291-4372-47a1-a535-1235f315c5e6)

Thanks.

**Comment by Cjl-MedSeg** [comment]
In the dataset.json file, the "modality" field indicates the modality to which the dataset belongs, such as CT for BTCV. The "labels" field represents the category labels of the dataset. It is important to note that the "imask" does not contain semantic information.

**Comment by lxa9867** [comment]
Hi, 

Thanks for the response. After downloading the datasets on the huggingface. I noticed the image count is about 1.1 M. Is that due to not all the datasets having been uploaded? Thanks.

**Comment by lxa9867** [comment]
I'd like to thank the author for the response.
